### ISSUE TITLE
Giant duplicate messages button when premium renewal button is present

### ISSUE THREAD

**Issue by ajs256** [magma1447/greasemonkey-geocaching-projectgc#100]
When your GC.com premium membership is within a month of expiring, a "Renew" button is added to the toolbar. This breaks the script's injected menu.
<img width="1446" alt="image" src="https://user-images.githubusercontent.com/67526318/124515964-8b305c00-dd95-11eb-9e08-fbf6792dd29d.png">
The button has classes of `cta-upgrade desktop-upgrade-cta`.

**Comment by magma1447** [comment]
It took me a while to realize that it's the premium membership at Geocaching.com that's expiring. You most likely meant that, I just read it wrong initially. This is a bit hard to fix due to the simple fact that it's hard to reproduce when your membership isn't close to expire.

If you have the knowledge, you are more than welcome to submit push requests.

**Comment by capoaira** [comment]
I think the bug is a result of my last change to support the new header.
I should get the Renew Button within the next few days. (How many days before expiry did you see the button @ajs256?)

**Comment by ajs256** [comment]
> How many days before expiry did you see the button?
A month.

**Comment by capoaira** [comment]
Hmm, I do not see the "Renew" button, but it is only a half moth to the Renewal Date...

**Comment by ajs256** [comment]
Well that's weird, I no longer see the button either! They must have pushed an update recently.

**Comment by capoaira** [comment]
I can reproduce the bug with a non-premium account. The fix comes in PR #101
