### ISSUE TITLE
Logs Summary line typo:  Extra single quote

### ISSUE THREAD

**Issue by rteitelman** [magma1447/greasemonkey-geocaching-projectgc#112]
The line right before the logs begin has a logs summary that looks like this:
View all logs (9) | Yours (1) | Friends' | View Gallery (1)
NOTE: Above line is for my view of GC9VGC

that value of Yours is wrong, I have 2 logs not 1. 
Friends' has no value. It should be 1. Godot is my friend with 1 log. I think that single ' is a typo after the word Friends

**Comment by jewettg** [comment]
@rteitelman  - I can not find a Geocache with the GC code of "GC9VGC".   So that is making it hard to debug.

I found where the single quote is showing up in the Friends link, and you are right, it is a code typo, as I can not think of a reason why that is there.  However, I can remove the single quote but it will not show the number afterwards.  I found where the log summary line is, and where it generates the text that it inserts, but I can not figure out where the numbers are coming from.  There is no obvious code that explains how that is being calculated or inserted.

I tried a couple of other cache pages, and "Yours" shows up as "1", not sure if that is correct or not, but Friends never calculates or displays a number.

I was going to roll this into 2.3.15; but I can not verify the issue.

**Comment by rteitelman** [comment]
Try,  #82 Bad to the Bone! Mystery Cache - GC8C0RY

It displays "Friends'" with no number, BUT if you click on that line, you'll see that gc.com  knows the number is 6.  So get the number from there?   Does that help?

**Comment by jewettg** [comment]
@rteitelman  - OK, I found the code that populates the number of Geocaches in "Yours (#)".  It is a ID tag that is updated with the preference:
- IsSettingEnabled('addMyNumberOfLogs')
- IsSettingEnabled('logbookLinks')

There is no such setting for calculating the number of friends logs; at least that I can find.  _Not that this can not be added, it just is not there yet._  **Please create a new feature request (issue) for this functionality.**

As for incorrect count, please find me a Geocache page that causes the script to display the incorrect number of "Yours(#)" logs.

This issue was for TWO things:
- Remove the typo of a single-quote that was showing up on "Friends'" log link.   (FIXED)
- A reported incorrect number of logs for "Yours (#)".   (Need to verify bug)

**Comment by rteitelman** [comment]
ok, new issue opened for this......titled: Incorrect "Yours" count on the
log summary line showing count of: All Logs, Yours, Friends, Gallery

**Comment by jewettg** [comment]
#115 now replaces the "A reported incorrect number of logs for "Yours (#)". (Need to verify bug)" part of this issue.  This issue is now just " Logs Summary line typo: Extra single quote #112"; and will be fixed and closed.
