### ISSUE TITLE
Setting to Parse EXIF information ?  still needed?

### ISSUE THREAD

**Issue by rteitelman** [magma1447/greasemonkey-geocaching-projectgc#123]
I interpret this to mean that any coordinates/location information displayed by a photo in the log will be supressed.    But didn't Geocaching.com fix this a long time ago, and EXIF location info is stripped out and no longer displayed?   I can't find someone's log to test with.

**Comment by magma1447** [comment]
To my knowledge only new images uploaded are affected by those changes. An example of an existing one can be found at http://coord.info/GC7CWEH. Look for the log by Ficher at 2018-03-13 (Y-M-D).

I agree that the code makes much less sense now. But it still provides a feature, and as long as there isn't an issue with it I don't see any reason to remove it.

I see that the placement of the inserted text could use some updated alignment though. Should probably be moved up a bit so that it exists inside the grey rectangle.

**Comment by rteitelman** [comment]
OK, I see now the EXIF location data on that old log from 2018-03-13 and also one from 2017-11-01.    If I uncheck the "Parse Exif location" setting, it is no longer displayed.  I would have to assume EXIF data on these old log photos is hardly ever used, so I say we just leave the code as is, even though the alignment is off on some logs.  I would however propose to change the wording of the setting to be clearer.

From: Parse Exif location
     To: Display EXIF location info on old log photos that have it

**Comment by rteitelman** [comment]
Not really going to worry that the placement of the inserted text is off in some places.  and the wording on the settings menu is modified in version 2.3.17
