### ISSUE TITLE
Do you want to leave geocaching.com -alert

### ISSUE THREAD

**Issue by magma1447** [magma1447/greasemonkey-geocaching-projectgc#35]
Geocaching.com now pops up a js alert when one clicks links on the Profile page, can we remove that whenever the link goes to project-gc.com?

A setting could be added to always remove that warning. But Project-GC.com should always be trusted.

Example link, clicking my PGC Profile stats at https://www.geocaching.com/profile/

**Comment by magma1447** [comment]
The one who fixes this will be given a coupon code for one year Membership at Project-GC. The value is 18 EUR, it can be used, sold or gifted.

Write a note here with your Geocaching.com name after a pull request has been made. After confirming the patch a coupon code will be sent via Project-GC.com.

**Comment by GeekNJ** [comment]
Took a look at this and seems the most elegant solution is to alter in-line javascript on the pages that calls a routine. The check should add (... || hostname == "project-gc.com || hostname == "www.project-gc.com") in the below snippet. Need to figure out how to make that happen in GreaseMonkey. 

var hostname = extractHostname(obj.message.href);
            **if (isGeocachingDomain(hostname)) {**
                window.open(obj.message.href, obj.message.target);
                return;
            }

**Comment by magma1447** [comment]
I am no GreaseMonkey expert, but I doubt you can. I really hope I am wrong though. I would assume the script is already loaded and modifications (if they can be made) won't be noticed. But again, you are welcome to prove me wrong. I know I played with it when I created this issue, but I couldn't figure out a smooth way to do it. Though adding to that list would be elegant, and hopefully a very stable change.

Today's Googling tells me that it might be possible with "beforescriptexecture event", http://stackoverflow.com/questions/10472569/changing-javascript-on-an-html-page-out-of-my-control

**Comment by GeekNJ** [comment]
I was trying not to override the base function isGeocachingDomain located in external js file https://www.geocaching.com/scripts/utilities.js since it could require more maintenance as geocaching.com changes. If there's no way to elegantly add it to the "if", an option to try is to duplicate/replace one of their functions with one that includes the pgc domains. 

Might not have more time to look at this until tonight.

**Comment by GeekNJ** [comment]
I have it coded as an override to the isGeocachingDomain function but need to validate that it still shows the pop-up for other domains. I can't find a cache page that will cause this link for a non-gc/non-project-gc link. Anyone have a cache page or URL that causes the pop-up I can test against?

Adding an option and overriding the pop-up for all links is easy to include as well if desired.

**Comment by GeekNJ** [comment]
I found a link - a profile page of a cacher that referenced another 3rd party URL. The code I cobbled together appears to work fine with just pgc links. Do you want me to commit that or do you want to add an additional option to also prevent the pop-up for all links?

The pop-up does NOT occur today on cache pages which is where I was testing and I've only found it on profile pages. The code I added handles it across ANY page. 

Let me know how you'd like to proceed.

**Comment by magma1447** [comment]
I think it's fine if it only fixes Project-GC.com-links. The setting for other sites might be bloated, we'll hold of on that.

Make a pull request and I'll have a look.

**Comment by magma1447** [comment]
@GeekNJ I have sent a reward to Jakuje, but I don't mind sending you one as well for the initial work. Please remind me of your geocaching.com-name and I will do so.

**Comment by GeekNJ** [comment]
@magma1447  - thanks for the offer but you just recently gave me a free year subscription so I'm good for quite some time. But thanks again and thanks to @Jakuje  for his much more elegant approach.

**Comment by Jakuje** [comment]
Well, we are not quite done yet. I just noticed, that the change is breaking the Map bookmarklist (and possibly other features), because the `isGeocachingDomain` is not defined on that page.

If I noticed well, this super-scary warning is used only on the profile page (does not apply for cache listings if I am right), therefore applying it only on `/profile/*` probably makes sense. I will give it a try with a new pull request.

**Comment by magma1447** [comment]
@Jakuje I actually noticed it myself today while making another non related fix. I was going to fix it myself before I made a release of my own fix, but I forgot. :/

I think it makes sense to only apply it to /profile/* as you say. The alternative is to check that isGeocachingDomain is defined before using it.

**Comment by GeekNJ** [comment]
In my initial inelegant approach, isGeocachingDomain was always defined. I
had originally noticed it was on the profile page because I was going crazy
testing on a cache detail page and wondering why it wasn't popping up the
alert for all those external links. Seems silly they just implemented on
the profile page. I'd agree with just /profile/* for now as well.
