### ISSUE TITLE
Exif parser wrong display value

### ISSUE THREAD

**Issue by magma1447** [magma1447/greasemonkey-geocaching-projectgc#59]
On cache http://coord.info/GC77Y8D there is a log by ganja1447 (me) with several log images. Two of those are displayed as having a geotag of **N55 52.1000 E012 49.767**. Not sure what the correct value should be, but definitely not 52.1000.

**Comment by sdahlbac** [comment]
I took a quick look, the coordinates in the file is 55.883333, 12.829444 => N 55 53.000, E 012 49.767

Based on the looks of it, the issue is in GetCoordinatesFromExif, and a float/rounding issue at that

![image](https://user-images.githubusercontent.com/659363/27929776-ef766d12-629c-11e7-8e78-18ba4310ff1e.png)

At the moment I'm not really sure what the correct fix is, so if anyone else has an idea, feel free.

**Comment by magma1447** [comment]
Fixed by merge.
